-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 22:13:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoGames
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancoGames` ;

-- -----------------------------------------------------
-- Schema bancoGames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoGames` DEFAULT CHARACTER SET utf8 ;
USE `bancoGames` ;

-- -----------------------------------------------------
-- Table `bancoGames`.`publicoAlvo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`publicoAlvo` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`publicoAlvo` (
  `idPublicoAlvo` INT NOT NULL,
  `faixaEtaria` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPublicoAlvo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`Engine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`Engine` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`Engine` (
  `idEngine` INT NOT NULL,
  `nomeEngine` VARCHAR(45) NOT NULL,
  `siteEngine` VARCHAR(200) NOT NULL,
  `lingProg` VARCHAR(45) NOT NULL,
  `licencaEngine` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEngine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`produtora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`produtora` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`produtora` (
  `idProdutora` INT NOT NULL,
  `nomeProdutora` VARCHAR(100) NOT NULL,
  `site` VARCHAR(255) NOT NULL,
  `anoFundação` DATE NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProdutora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`Jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`Jogo` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`Jogo` (
  `idJogo` INT NOT NULL AUTO_INCREMENT,
  `tituloJogo` VARCHAR(100) NOT NULL,
  `descricaoJogo` VARCHAR(250) NOT NULL,
  `preco` FLOAT NOT NULL,
  `multiplayer` TINYINT NOT NULL,
  `publicoAlvo_idPublicoAlvo` INT NOT NULL,
  `Engine_idEngine` INT NOT NULL,
  `produtora_idProdutora` INT NOT NULL,
  PRIMARY KEY (`idJogo`),
  INDEX `fk_Jogo_publicoAlvo1_idx` (`publicoAlvo_idPublicoAlvo` ASC) VISIBLE,
  INDEX `fk_Jogo_Engine1_idx` (`Engine_idEngine` ASC) VISIBLE,
  INDEX `fk_Jogo_produtora1_idx` (`produtora_idProdutora` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_publicoAlvo1`
    FOREIGN KEY (`publicoAlvo_idPublicoAlvo`)
    REFERENCES `bancoGames`.`publicoAlvo` (`idPublicoAlvo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_Engine1`
    FOREIGN KEY (`Engine_idEngine`)
    REFERENCES `bancoGames`.`Engine` (`idEngine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_produtora1`
    FOREIGN KEY (`produtora_idProdutora`)
    REFERENCES `bancoGames`.`produtora` (`idProdutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`Email` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`Email` (
  `idEmail` INT NOT NULL,
  `TipoEmail` VARCHAR(200) NOT NULL,
  `email` VARCHAR(240) NOT NULL,
  `idProdutora` INT NOT NULL,
  PRIMARY KEY (`idEmail`),
  INDEX `idProdutora_idx` (`idProdutora` ASC) VISIBLE,
  CONSTRAINT `idProdutora`
    FOREIGN KEY (`idProdutora`)
    REFERENCES `bancoGames`.`produtora` (`idProdutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`genero` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`genero` (
  `idgenero` INT NOT NULL,
  `nomeGenero` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoGames`.`JogoGenero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`JogoGenero` ;

CREATE TABLE IF NOT EXISTS `bancoGames`.`JogoGenero` (
  `Jogo_idJogo` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`Jogo_idJogo`, `genero_idgenero`),
  INDEX `fk_Jogo_has_genero_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_Jogo_has_genero_Jogo_idx` (`Jogo_idJogo` ASC) VISIBLE,
  CONSTRAINT `fk_Jogo_has_genero_Jogo`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `bancoGames`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `bancoGames`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bancoGames` ;

-- -----------------------------------------------------
-- Placeholder table for view `bancoGames`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoGames`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `bancoGames`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancoGames`.`view1`;
DROP VIEW IF EXISTS `bancoGames`.`view1` ;
USE `bancoGames`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
